### ISSUE TITLE
使用wifi(只有广电网络)时，不可用

### ISSUE THREAD

**Issue by hukangha** [Shadowrocket/manual#11]
hi，你好，
我在使用最近的版本 2.1.26(739) ，iphone 7
这个现象不止发生在此版本，看不出来问题是否出现在 shadowrocket ，不过还是在这里问一下吧。
广电网络 wifi 本身是没问题的，macbook wifi + ssr 正常。
ssr 服务器也没问题，手机切4G ssr 正常。
手机 wifi 看起来似乎也没问题，在其他 wifi 下 ssr 正常。
只有在广电网络的 wifi 下 手机 ssr 出问题。
log 我看不太出来问题在哪。
把 log 贴在这，麻烦帮忙分析一下问题在哪。
谢谢！
[log.zip](https://github.com/Shadowrocket/manual/files/3316456/log.zip)

--
偶尔还是正常的，大概率挂掉，小概率恢复正常

**Comment by cute** [comment]
一般是dns查询失败，除了system，可以在dns-server添加公共dns试试，比如114.114.114.114。
